version: '3'

services:
  gogs:
    image: gogs/gogs-rpi
    volumes:
      - ./gogs:/data
    ports:
      - "3000:3000"
      - "10022:22"

  drone-server:
    image: drone/drone:1
    ports:
      - "8080:80"
    volumes:
      - ./drone:/data
    restart: always
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=drone-server
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_TLS_AUTOCERT=false 
      - DRONE_RPC_SECRET=00f5b2851bb047a27cf6378b53142e35529f469c
      - DRONE_GOGS_SERVER_PROTO=http

  drone-agent:
    image: drone/agent:1
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:8080
      - DRONE_RPC_SECRET=00f5b2851bb047a27cf6378b53142e35529f469c
      - DRONE_DEBUG=true
