version: '3'

services:
  gogs:
    image: gogs/gogs-rpi
    volumes:
      - ./gogs:/data
    ports:
      - "3000:3000"

  drone-server:
    image: drone/drone:1
    ports:
      - "8000:8000"
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server:8000
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_DEBUG=true
      - DRONE_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_GOGS=true
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_GOGS_PRIVATE_MODE=true

  drone-agent:
    image: drone/agent:1
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_DEBUG=true
